// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootScanGetData = {
    query: {
        qr_code: string;
    };
};

export type RootScanGetResponse = (unknown);

export type RootScanGetError = (HTTPValidationError);