"""add disabled status in item

Revision ID: 09651e2066f3
Revises: 181ceec64aaf
Create Date: 2024-12-25 21:46:13.681748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09651e2066f3'
down_revision: Union[str, None] = '181ceec64aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'disabled')
    # ### end Alembic commands ###
