"""fix expire type

Revision ID: 772d37482e23
Revises: e7fba38ede7b
Create Date: 2024-12-15 10:49:14.064666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '772d37482e23'
down_revision: Union[str, None] = 'e7fba38ede7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_password', 'expire',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_password', 'expire',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
