"""add store_id in order

Revision ID: c512483bbc51
Revises: c5b41d52856e
Create Date: 2024-12-14 13:43:12.216748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision: str = 'c512483bbc51'
down_revision: Union[str, None] = 'c5b41d52856e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('store_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False)            , default=uuid.uuid4, nullable=False))
    op.create_foreign_key(None, 'order', 'store', ['store_id'], ['store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'store_id')
    # ### end Alembic commands ###
