"""add phone in organization and store

Revision ID: e1ddef123e7f
Revises: 4259a72aef38
Create Date: 2024-12-03 06:14:34.552402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ddef123e7f'
down_revision: Union[str, None] = '4259a72aef38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('phone', sa.String(length=11), nullable=False))
    op.add_column('store', sa.Column('phone', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'phone')
    op.drop_column('organization', 'phone')
    # ### end Alembic commands ###
