"""add reset password table

Revision ID: e7fba38ede7b
Revises: c512483bbc51
Create Date: 2024-12-15 10:44:25.672103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision: str = 'e7fba38ede7b'
down_revision: Union[str, None] = 'c512483bbc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password',
    sa.Column('reset_password_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False)            , default=uuid.uuid4, nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('token', sa.String(length=1137), nullable=False),
    sa.Column('expire', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reset_password_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_password')
    # ### end Alembic commands ###
